version: "3.9"

services:
  db:
    image: postgres:alpine
    container_name: userMenagement-db
    restart: always
    tty: true
    ports:
      - "5433:5432"  # O host (5433) está mapeado para a porta do container (5432)
    volumes:
      - ./../.db/postgres/data:/var/lib/postgresql/data  # O volume está configurado corretamente
    environment:
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: userMenagementDB

      

