@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGhldXMyMDAyaGJsQGhvdG1haWwuY29tIiwiZXhwIjoxNzQ2MDQ2MzA0LCJuYW1lIjoiTWF0aGV1cyBMZW1vcyBVc3VhcmlvIiwidXNlcl9pZCI6ImYzNzUwNTA4LTA4MDgtNDdmZS04MGQ1LWMwNzgyMGRjOTRlYyJ9.A-mZ_YKBnoa273eKrNSd3CR9be91xHlCupCHDo_FNXQ

### Criar usuário
POST http://localhost:5000/gymcontoll/api/v1/user
Content-Type: application/json

{
  "name": "Matheus Lemos Usuario",
  "password": "1234",
  "email": "matheus2002hbl@hotmail.com",
  "birthday": "1972-01-19T16:00:00Z",
  "gender": "M",
  "acountype": "gym_manager"
}

###
### Login (retorna token JWT)
POST http://localhost:5000/gymcontoll/api/v1/login
Content-Type: application/json

{
  "email": "matheus2002hbl@hotmail.com",
  "password": "1234"
}

###
### Buscar todos os usuários
GET http://localhost:5000/gymcontoll/api/v1/users
Authorization: Bearer {{token}}

###
### Buscar usuário por ID
GET http://localhost:5000/gymcontoll/api/v1/user/f3750508-0808-47fe-80d5-c07820dc94ec
Authorization: Bearer {{token}}

###
### Atualizar usuário (completo)
PUT http://localhost:5000/gymcontoll/api/v1/user/55aa3dfd-a0ca-4b3b-90bf-fa6befb807dc
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Matheus Atualizado",
  "password": "novaSenha123",
  "email": "matheus_atualizado@hotmail.com",
  "birthday": "1990-02-10T00:00:00Z",
  "gender": "M",
  "acountype": "default_user"
}

###
### Atualização parcial
PUT http://localhost:5000/gymcontoll/api/v1/user/55aa3dfd-a0ca-4b3b-90bf-fa6befb807dc
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "acountype": "default_user"
}

###
### Exclusão lógica do usuário
PUT http://localhost:5000/gymcontoll/api/v1/deleteuser/55aa3dfd-a0ca-4b3b-90bf-fa6befb807dc
Authorization: Bearer {{token}}

###
### Criar exercício
POST http://localhost:5000/gymcontoll/api/v1/exercice
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Agachamento Hack",
  "muscle": "Pernas",
  "description": "Exercício composto para membros inferiores",
  "equipment": "Barra",
  "video_url": "https://youtu.be/agachamento"
}


### EXERCICIOS

### Buscar todos os exercícios
GET http://localhost:5000/gymcontoll/api/v1/
Authorization: Bearer {{token}}

###
### Buscar exercício por ID
GET http://localhost:5000/gymcontoll/api/v1/exercice/EXERCICE_ID_AQUI
Authorization: Bearer {{token}}

###
### Atualizar exercício
PUT http://localhost:5000/gymcontoll/api/v1/exercice/EXERCICE_ID_AQUI
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Agachamento Hack",
  "muscle": "Pernas",
}

###
### Excluir exercício
DELETE http://localhost:5000/gymcontoll/api/v1/exercice/EXERCICE_ID_AQUI
Authorization: Bearer {{token}}