POST http://localhost:5000/gymcontoll/api/v1/user HTTP/1.1
Content-Type: application/json

{
  "name": "Matheus Lemos Usuario",
  "password": "1234",
  "email": "matheus2002hbl@hotmail.com",
  "birthday": "1972-01-19T16:00:00Z",
  "gender": "M",
  "acountype": "gym_manager"
}
###

GET http://localhost:5000/gymcontoll/api/v1/users

###
GET http://localhost:5000/gymcontoll/api/v1/user/55aa3dfd-a0ca-4b3b-90bf-fa6befb807dc

###
PUT http://localhost:5000/gymcontoll/api/v1/user/55aa3dfd-a0ca-4b3b-90bf-fa6befb807dc
Content-Type: application/json

{
  "acountype": "default_user"
}
###
PUT  http://localhost:5000/gymcontoll/api/v1/deleteuser/55aa3dfd-a0ca-4b3b-90bf-fa6befb807dc
