GYMCONTROL_WEBSERVER_PORT = 3000
GYMCONTROL_DB_USER = "pguser"
GYMCONTROL_DB_SERVER = "localhost"
GYMCONTROL_DB_SERVERPORT = "5433"
GYMCONTROL_DB_PASSWORD = "pgpass"
GYMCONTROL_DB_DATABASE = "permissao"
